### ISSUE TITLE
Custom props support

### ISSUE THREAD

**Issue by answer261** [single-spa/single-spa-html#4]
Hey, I have one question regarding custom props support. 

Single-spa supports custom props by passing them to 'registerApplication' method :
https://single-spa.js.org/docs/building-applications#custom-props.

Is there any way to pass such props to a web component which is part of a template string?

**Comment by internettrans** [comment]
Currently, no. See https://github.com/CanopyTax/single-spa-html/blob/e71fb9626658c642ad060a34cf2a92c3f66a9c02/src/single-spa-html.js#L45

However, if you're okay with just string attributes being passed in, this is something that could be accomplished by allowing the `template` option to be a function instead of a string:

```js
singleSpaHtml({
  template: props => `
    <some-custom-element thing=${props.thing} />
  `
})
```

If having this would be interesting to you, I'd be happy to review a PR that adds this functionality.

**Comment by answer261** [comment]
Hey @joeldenning. 
That's actually a great idea. 
Already prepared the branch with this improvement but I don't have permissions to push it, can you please help me with it?

**Comment by internettrans** [comment]
You should [create a fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) of this repo and push to your fork. Then you'll be able to create a pull request from your fork into the main repo.

Happy to give you write permissions to this repo after one or two PRs are merged!

**Comment by answer261** [comment]
Thanks for the tip.

https://github.com/CanopyTax/single-spa-html/pull/5

**Comment by internettrans** [comment]
Thanks for the PR - released in https://github.com/CanopyTax/single-spa-html/releases/tag/v1.1.1

**Comment by internettrans** [comment]
I created https://github.com/CanopyTax/single-spa.js.org/pull/126 to update the documentation for this
